#![forbid(unsafe_code)]

use std::collections::VecDeque;

/// A permutation in images notation. p[i] = image of i under the permutation.
/// Indices are 0-based internally. The identity permutation of degree n is [0, 1, 2, ..., n-1].
pub type Perm = Vec<usize>;

/// Result of the Schreier-Sims algorithm.
#[derive(Clone, Debug)]
pub struct SGS {
    pub base: Vec<usize>,
    pub generators: Vec<Perm>,
    pub n: usize,
}

/// Create the identity permutation of degree n.
pub fn identity(n: usize) -> Perm {
    (0..n).collect()
}

/// Check if a permutation is the identity.
pub fn is_identity(p: &[usize]) -> bool {
    p.iter().enumerate().all(|(i, image)| *image == i)
}

/// Compute the product (composition) of two permutations: result[i] = p2[p1[i]].
/// Both must have the same degree.
pub fn product(p1: &[usize], p2: &[usize]) -> Perm {
    assert_eq!(p1.len(), p2.len(), "permutations must have the same degree");
    (0..p1.len()).map(|i| p2[p1[i]]).collect()
}

/// Compute the inverse of a permutation.
pub fn inverse(p: &[usize]) -> Perm {
    let mut inv = vec![0; p.len()];
    for (i, image) in p.iter().enumerate() {
        inv[*image] = i;
    }
    inv
}

/// Apply a permutation to a point: return p[point].
pub fn on_points(point: usize, p: &[usize]) -> usize {
    p[point]
}

/// Find all points fixed by the permutation (p[i] == i).
pub fn stable_points(p: &[usize]) -> Vec<usize> {
    p.iter()
        .enumerate()
        .filter_map(|(i, image)| (*image == i).then_some(i))
        .collect()
}

/// Find the first point NOT fixed by the permutation. Returns None if identity.
pub fn first_nonstable_point(p: &[usize]) -> Option<usize> {
    p.iter()
        .enumerate()
        .find_map(|(i, image)| (*image != i).then_some(i))
}

/// Compute the orbit of a point under a set of generators.
/// Returns the set of all points reachable from `point` by applying generators.
pub fn orbit(point: usize, generators: &[Perm]) -> Vec<usize> {
    let n = generators
        .iter()
        .map(|g| g.len())
        .max()
        .unwrap_or(point.saturating_add(1));
    let mut seen = vec![false; n];
    let mut queue = VecDeque::new();
    let inverses: Vec<Perm> = generators.iter().map(|g| inverse(g)).collect();

    if point < n {
        seen[point] = true;
        queue.push_back(point);
    }

    while let Some(current) = queue.pop_front() {
        for generator in generators {
            let next = on_points(current, generator);
            if !seen[next] {
                seen[next] = true;
                queue.push_back(next);
            }
        }
        for generator in &inverses {
            let next = on_points(current, generator);
            if !seen[next] {
                seen[next] = true;
                queue.push_back(next);
            }
        }
    }

    seen.iter()
        .enumerate()
        .filter_map(|(i, reached)| (*reached).then_some(i))
        .collect()
}

/// Compute all orbits of the group generated by `generators` on {0, 1, ..., n-1}.
/// Returns a Vec where orbits[i] is the orbit number of point i.
pub fn all_orbits(generators: &[Perm], n: usize) -> Vec<usize> {
    let mut labels = vec![usize::MAX; n];
    let mut orbit_id = 0usize;
    for point in 0..n {
        if labels[point] != usize::MAX {
            continue;
        }
        for member in orbit(point, generators) {
            labels[member] = orbit_id;
        }
        orbit_id += 1;
    }
    labels
}

/// Compute a Schreier vector for `point` under `generators`.
/// Returns (nu, w) where:
/// - nu[i] is the point that maps to i on the path from `point` to i
/// - w[i] is the index of the generator used (or usize::MAX if not reached)
/// Together they encode the path from `point` to any point in its orbit.
pub fn schreier_vector(point: usize, generators: &[Perm], n: usize) -> (Vec<usize>, Vec<usize>) {
    let mut nu = vec![usize::MAX; n];
    let mut w = vec![usize::MAX; n];
    let mut seen = vec![false; n];
    let mut queue = VecDeque::new();

    if point < n {
        seen[point] = true;
        nu[point] = point;
        queue.push_back(point);
    }

    while let Some(current) = queue.pop_front() {
        for (gen_index, generator) in generators.iter().enumerate() {
            let next = on_points(current, generator);
            if !seen[next] {
                seen[next] = true;
                nu[next] = current;
                w[next] = gen_index;
                queue.push_back(next);
            }
        }
    }

    (nu, w)
}

/// Trace back through a Schreier vector to find the group element
/// that maps `point` to `target`. Returns the permutation.
pub fn trace_schreier(
    target: usize,
    point: usize,
    nu: &[usize],
    w: &[usize],
    generators: &[Perm],
    n: usize,
) -> Perm {
    if target >= n || point >= n || nu.get(target).copied().unwrap_or(usize::MAX) == usize::MAX {
        return identity(n);
    }
    let mut current = target;
    let mut trace = identity(n);
    while current != point {
        let gen_index = w[current];
        if gen_index == usize::MAX {
            return identity(n);
        }
        let generator = generators[gen_index].clone();
        trace = product(&generator, &trace);
        current = nu[current];
    }
    trace
}

fn fixes_all(points: &[usize], p: &[usize]) -> bool {
    points.iter().all(|point| p[*point] == *point)
}

fn contains_perm(perms: &[Perm], candidate: &[usize]) -> bool {
    perms.iter().any(|perm| perm == candidate)
}

/// Compute the stabilizer subgroup of a set of points.
/// Given generators of a group G, return generators of Stab_G(points).
pub fn stabilizer(points: &[usize], generators: &[Perm], n: usize) -> Vec<Perm> {
    let mut stabilizer_gens = Vec::new();

    for generator in generators {
        if fixes_all(points, generator) && !contains_perm(&stabilizer_gens, generator) {
            stabilizer_gens.push(generator.clone());
        }
    }

    if points.is_empty() {
        return stabilizer_gens;
    }

    let base = points[0];
    let schreier_gens = extended_generators(generators);
    let (nu, w) = schreier_vector(base, &schreier_gens, n);
    let orbit_points: Vec<usize> = (0..n)
        .filter(|point| nu[*point] != usize::MAX)
        .collect();

    for orbit_point in orbit_points {
        let trace_to_orbit = trace_schreier(orbit_point, base, &nu, &w, &schreier_gens, n);
        for generator in generators {
            let moved = on_points(orbit_point, generator);
            if moved >= n || nu[moved] == usize::MAX {
                continue;
            }
            let trace_to_moved = trace_schreier(moved, base, &nu, &w, &schreier_gens, n);
            let schreier_gen = product(
                &product(&trace_to_orbit, generator),
                &inverse(&trace_to_moved),
            );
            if fixes_all(points, &schreier_gen) && !is_identity(&schreier_gen) && !contains_perm(&stabilizer_gens, &schreier_gen) {
                stabilizer_gens.push(schreier_gen);
            }
        }
    }

    stabilizer_gens
}

/// Count the number of inversions in a permutation (for computing sign).
pub fn sign(p: &[usize]) -> i32 {
    let mut inversions = 0usize;
    for i in 0..p.len() {
        for j in (i + 1)..p.len() {
            if p[i] > p[j] {
                inversions += 1;
            }
        }
    }
    if inversions % 2 == 0 { 1 } else { -1 }
}

/// Create a transposition: swaps positions i and j, fixes everything else.
pub fn transposition(n: usize, i: usize, j: usize) -> Perm {
    let mut p = identity(n);
    p.swap(i, j);
    p
}

fn stabilizer_generators_for_level(base: &[usize], level: usize, generators: &[Perm]) -> Vec<Perm> {
    generators
        .iter()
        .filter(|g| base[..level].iter().all(|&b| on_points(b, g) == b))
        .cloned()
        .collect()
}

fn extended_generators(generators: &[Perm]) -> Vec<Perm> {
    let mut extended = generators.to_vec();
    for inverse_gen in generators.iter().map(|g| inverse(g)) {
        if !contains_perm(&extended, &inverse_gen) {
            extended.push(inverse_gen);
        }
    }
    extended
}

fn generated_group(generators: &[Perm], n: usize) -> Vec<Perm> {
    let mut elements = vec![identity(n)];
    let mut queue = VecDeque::from([identity(n)]);
    let extended = extended_generators(generators);

    while let Some(current) = queue.pop_front() {
        for generator in &extended {
            let next = product(&current, generator);
            if !contains_perm(&elements, &next) {
                elements.push(next.clone());
                queue.push_back(next);
            }
        }
    }

    elements
}

/// Sift a permutation through the stabilizer chain.
/// Returns true if the permutation is already in the group (sifts to identity).
fn sift(perm: &[usize], base: &[usize], generators: &[Perm], n: usize) -> bool {
    let mut current = perm.to_vec();

    for (level, &bp) in base.iter().enumerate() {
        let img = on_points(bp, &current);
        if img == bp {
            continue;
        }

        let stab_gens = stabilizer_generators_for_level(base, level, generators);
        let schreier_gens = extended_generators(&stab_gens);
        let (nu, w) = schreier_vector(bp, &schreier_gens, n);
        if nu.get(img).copied().unwrap_or(usize::MAX) == usize::MAX {
            return false;
        }

        let rep = trace_schreier(img, bp, &nu, &w, &schreier_gens, n);
        current = product(&current, &inverse(&rep));
    }

    is_identity(&current)
}

/// Compute a Strong Generating Set from generators.
///
/// Input: initial base hint (can be empty), generators, degree n.
/// Output: SGS with a valid base and strong generating set.
pub fn schreier_sims(
    base_hint: &[usize],
    generators: &[Perm],
    n: usize,
) -> SGS {
    if generators.is_empty() {
        return SGS {
            base: vec![],
            generators: vec![],
            n,
        };
    }

    let mut base: Vec<usize> = base_hint.to_vec();
    let mut strong_gens: Vec<Perm> = generators.to_vec();

    for generator in generators {
        for (i, &img) in generator.iter().enumerate() {
            if img != i && !base.contains(&i) {
                base.push(i);
            }
        }
    }

    let mut seen = std::collections::HashSet::new();
    base.retain(|x| seen.insert(*x));

    let mut changed = true;
    let mut iteration = 0usize;
    let max_iterations = 100usize;

    while changed && iteration < max_iterations {
        changed = false;
        iteration += 1;

        for level in (0..base.len()).rev() {
            let stab_gens = stabilizer_generators_for_level(&base, level, &strong_gens);
            if stab_gens.is_empty() {
                continue;
            }

            let bp = base[level];
            let schreier_gens = extended_generators(&stab_gens);
            let (nu, w) = schreier_vector(bp, &schreier_gens, n);
            let orb = orbit(bp, &stab_gens);

            for &gamma in &orb {
                for generator in &stab_gens {
                    let gen_gamma = on_points(gamma, generator);
                    let trace_gamma = trace_schreier(gamma, bp, &nu, &w, &schreier_gens, n);
                    let trace_gen_gamma =
                        trace_schreier(gen_gamma, bp, &nu, &w, &schreier_gens, n);

                    let schreier_gen = product(
                        &product(&inverse(&trace_gen_gamma), generator),
                        &trace_gamma,
                    );

                    if !is_identity(&schreier_gen)
                        && !contains_perm(&strong_gens, &schreier_gen)
                        && !sift(&schreier_gen, &base, &strong_gens, n)
                    {
                        strong_gens.push(schreier_gen);
                        changed = true;
                    }
                }
            }
        }
    }

    strong_gens = generated_group(&strong_gens, n)
        .into_iter()
        .filter(|g| !is_identity(g))
        .collect();

    SGS {
        base,
        generators: strong_gens,
        n,
    }
}

/// Test membership in the group.
pub fn is_member(perm: &[usize], sgs: &SGS) -> bool {
    sift(perm, &sgs.base, &sgs.generators, sgs.n)
}

/// Compute the order of the group from its SGS.
pub fn group_order(sgs: &SGS) -> u64 {
    let mut order = 1u64;
    for (level, &bp) in sgs.base.iter().enumerate() {
        let stab_gens = stabilizer_generators_for_level(&sgs.base, level, &sgs.generators);
        let orb = orbit(bp, &stab_gens);
        order *= orb.len() as u64;
    }
    order
}

fn compare_on_free_indices(a: &[usize], b: &[usize], free_indices: &[usize]) -> std::cmp::Ordering {
    for &idx in free_indices {
        match (a.get(idx), b.get(idx)) {
            (Some(lhs), Some(rhs)) => match lhs.cmp(rhs) {
                std::cmp::Ordering::Equal => {}
                non_eq => return non_eq,
            },
            _ => {}
        }
    }
    a.cmp(b)
}

fn choose_better(
    candidate: Perm,
    current_best: Option<Perm>,
    free_indices: &[usize],
) -> Option<Perm> {
    match current_best {
        None => Some(candidate),
        Some(best) => {
            let ordering = if free_indices.is_empty() {
                candidate.cmp(&best)
            } else {
                compare_on_free_indices(&candidate, &best, free_indices)
            };
            if ordering == std::cmp::Ordering::Less {
                Some(candidate)
            } else {
                Some(best)
            }
        }
    }
}

fn coset_representative_backtrack(
    current: &[usize],
    sgs: &SGS,
    level: usize,
    free_indices: &[usize],
) -> Perm {
    if level >= sgs.base.len() {
        return current.to_vec();
    }

    let bp = sgs.base[level];
    let level_gens = stabilizer_generators_for_level(&sgs.base, level, &sgs.generators);
    if level_gens.is_empty() {
        return coset_representative_backtrack(current, sgs, level + 1, free_indices);
    }

    let schreier_gens = extended_generators(&level_gens);
    let (nu, w) = schreier_vector(bp, &schreier_gens, sgs.n);
    let orbit_points = orbit(bp, &level_gens);
    let min_image = orbit_points
        .iter()
        .map(|&pt| current[pt])
        .min()
        .unwrap_or(current[bp]);

    let mut best = None;
    for &pt in &orbit_points {
        if current[pt] != min_image {
            continue;
        }
        let rep = trace_schreier(pt, bp, &nu, &w, &schreier_gens, sgs.n);
        let next = apply_group_action(current, &rep);
        let candidate = coset_representative_backtrack(&next, sgs, level + 1, free_indices);
        best = choose_better(candidate, best, free_indices);
    }

    best.unwrap_or_else(|| current.to_vec())
}

/// Compute the coset representative of a permutation relative to a subgroup.
/// Given perm and a group (base, generators), find the unique coset representative
/// cr such that perm = cr * h for some h in the group.
/// The representative is the lexicographically smallest element in the coset.
pub fn coset_representative(
    perm: &[usize],
    sgs: &SGS,
    free_indices: &[usize],
) -> Perm {
    coset_representative_backtrack(perm, sgs, 0, free_indices)
}

fn apply_group_action(perm: &[usize], g: &[usize]) -> Perm {
    (0..perm.len()).map(|i| perm[on_points(i, g)]).collect()
}

fn extract_sign_from_perm(perm: &[usize], sign_slots: Option<(usize, usize)>) -> i32 {
    match sign_slots {
        Some((i, j)) if i < perm.len() && j < perm.len() && perm[i] > perm[j] => -1,
        _ => 1,
    }
}

fn canonical_perm_backtrack(
    perm: &[usize],
    sgs: &SGS,
    dummy_pairs: &[(usize, usize)],
) -> (Perm, i32) {
    fn recurse(
        current: &[usize],
        sgs: &SGS,
        level: usize,
        dummy_pairs: &[(usize, usize)],
    ) -> Perm {
        if level >= sgs.base.len() {
            let mut leaf = current.to_vec();
            for &(d1, d2) in dummy_pairs {
                if d1 < leaf.len() && d2 < leaf.len() && leaf[d1] > leaf[d2] {
                    leaf.swap(d1, d2);
                }
            }
            return leaf;
        }

        let bp = sgs.base[level];
        let level_gens = stabilizer_generators_for_level(&sgs.base, level, &sgs.generators);
        if level_gens.is_empty() {
            return recurse(current, sgs, level + 1, dummy_pairs);
        }

        let schreier_gens = extended_generators(&level_gens);
        let (nu, w) = schreier_vector(bp, &schreier_gens, sgs.n);
        let orbit_points = orbit(bp, &level_gens);
        let min_image = orbit_points
            .iter()
            .map(|&pt| current[pt])
            .min()
            .unwrap_or(current[bp]);

        let mut best: Option<Perm> = None;
        for &pt in &orbit_points {
            if current[pt] != min_image {
                continue;
            }
            let rep = trace_schreier(pt, bp, &nu, &w, &schreier_gens, sgs.n);
            let next = apply_group_action(current, &rep);
            let candidate = recurse(&next, sgs, level + 1, dummy_pairs);
            best = choose_better(candidate, best, &[]);
        }

        best.unwrap_or_else(|| current.to_vec())
    }

    let best = recurse(perm, sgs, 0, dummy_pairs);
    let sign_slots = (sgs.n >= 2).then_some((sgs.n - 2, sgs.n - 1));
    let sign = extract_sign_from_perm(&best, sign_slots);
    (best, sign)
}

/// Find the lexicographically smallest permutation in the orbit of `perm` under the
/// group generated by `sgs`. This is the canonical form.
///
/// Also handles a sign slot: the last two elements of the permutation
/// encode the sign. If they're swapped relative to [n, n+1], the expression
/// picks up a minus sign.
pub fn canonical_perm(
    perm: &[usize],
    sgs: &SGS,
    dummy_pairs: &[(usize, usize)],
) -> (Perm, i32) {
    if sgs.generators.is_empty() {
        return (perm.to_vec(), 1);
    }
    canonical_perm_backtrack(perm, sgs, dummy_pairs)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn identity_is_identity() {
        let id = identity(5);
        assert!(is_identity(&id));
    }

    #[test]
    fn product_with_identity() {
        let id = identity(4);
        let p = vec![1, 0, 3, 2];
        assert_eq!(product(&p, &id), p);
        assert_eq!(product(&id, &p), p);
    }

    #[test]
    fn inverse_undoes() {
        let p = vec![1, 2, 0, 3];
        let ip = inverse(&p);
        let result = product(&p, &ip);
        assert!(is_identity(&result));
    }

    #[test]
    fn orbit_of_cycle() {
        let gen = vec![vec![1, 2, 0, 3]];
        let orb = orbit(0, &gen);
        assert_eq!(orb.len(), 3);
        assert!(orb.contains(&0));
        assert!(orb.contains(&1));
        assert!(orb.contains(&2));
    }

    #[test]
    fn sign_of_transposition() {
        let p = transposition(4, 0, 1);
        assert_eq!(sign(&p), -1);
    }

    #[test]
    fn sign_of_identity() {
        assert_eq!(sign(&identity(5)), 1);
    }

    #[test]
    fn sign_of_3cycle() {
        let p = vec![1, 2, 0, 3];
        assert_eq!(sign(&p), 1);
    }

    #[test]
    fn stabilizer_of_point() {
        let gens = vec![vec![1, 0, 2], vec![0, 2, 1]];
        let stab = stabilizer(&[0], &gens, 3);
        for g in &stab {
            assert_eq!(g[0], 0, "stabilizer element doesn't fix 0: {:?}", g);
        }
    }

    #[test]
    fn sgs_of_s3() {
        let gens = vec![vec![1, 0, 2], vec![0, 2, 1]];
        let sgs = schreier_sims(&[], &gens, 3);
        assert_eq!(group_order(&sgs), 6);
    }

    #[test]
    fn sgs_of_z2() {
        let gens = vec![vec![1, 0]];
        let sgs = schreier_sims(&[], &gens, 2);
        assert_eq!(group_order(&sgs), 2);
    }

    #[test]
    fn sgs_of_s4() {
        let gens = vec![
            vec![1, 0, 2, 3],
            vec![0, 2, 1, 3],
            vec![0, 1, 3, 2],
        ];
        let sgs = schreier_sims(&[], &gens, 4);
        assert_eq!(group_order(&sgs), 24);
    }

    #[test]
    fn membership_test() {
        let gens = vec![vec![1, 0, 2], vec![0, 2, 1]];
        let sgs = schreier_sims(&[], &gens, 3);

        let perm = vec![2, 0, 1];
        assert!(is_member(&perm, &sgs));
        assert!(is_member(&identity(3), &sgs));
    }

    #[test]
    fn empty_group() {
        let sgs = schreier_sims(&[], &[], 3);
        assert_eq!(group_order(&sgs), 1);
    }

    #[test]
    fn canonical_perm_symmetric_tensor() {
        let gens = vec![vec![1, 0]];
        let sgs = schreier_sims(&[0], &gens, 2);

        let (canon, sign) = canonical_perm(&[1, 0], &sgs, &[]);
        assert_eq!(canon, vec![0, 1]);
        assert_eq!(sign, 1);
    }

    #[test]
    fn canonical_perm_antisymmetric_tensor() {
        let gens = vec![vec![1, 0, 3, 2]];
        let sgs = schreier_sims(&[0], &gens, 4);

        let (canon, _s) = canonical_perm(&[1, 0, 2, 3], &sgs, &[]);
        assert!(canon[0] <= canon[1] || (canon[0] == 0 && canon[1] == 1));
    }
}
