#![forbid(unsafe_code)]

pub mod dummy_group;

use rayon::prelude::*;
use std::collections::{HashSet, VecDeque};
use std::sync::atomic::{AtomicBool, Ordering as AtomicOrdering};

/// A permutation in images notation. p[i] = image of i under the permutation.
/// Indices are 0-based internally. The identity permutation of degree n is [0, 1, 2, ..., n-1].
pub type Perm = Vec<usize>;

/// Result of the Schreier-Sims algorithm.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SGS {
    pub base: Vec<usize>,
    pub generators: Vec<Perm>,
    pub n: usize,
}

/// Description of a set of dummy index pairs.
#[derive(Clone, Debug)]
pub struct DummySet {
    /// Pairs of slot positions that hold dummy indices.
    /// Each pair (a, b) means slots a and b contain a contracted pair.
    pub pairs: Vec<(usize, usize)>,
    /// Metric symmetry: +1 for symmetric metric, -1 for antisymmetric (spinor),
    /// 0 for no metric (fixed position indices).
    pub metric_symmetry: i32,
}

/// Description of repeated (coordinate/integer) indices.
#[derive(Clone, Debug)]
pub struct RepeatedSet {
    /// Positions of the repeated index occurrences.
    pub positions: Vec<usize>,
}

/// An entry in the ALPHA tree used by the double-coset algorithm.
#[derive(Clone, Debug)]
pub struct AlphaEntry {
    /// The list of intermediate slot assignments L.
    pub l: Vec<usize>,
    /// The accumulated S-element.
    pub s: Perm,
    /// The accumulated D-element.
    pub d: Perm,
    /// For each point p in 0..n, which ALPHA entry index does extending L with p lead to.
    /// `None` means not yet explored.
    pub children: Vec<Option<usize>>,
}

/// Create the identity permutation of degree n.
pub fn identity(n: usize) -> Perm {
    (0..n).collect()
}

/// Check if a permutation is the identity.
pub fn is_identity(p: &[usize]) -> bool {
    p.iter().enumerate().all(|(i, image)| *image == i)
}

/// Compute the product (composition) of two permutations: result[i] = p2[p1[i]].
/// Both must have the same degree.
pub fn product(p1: &[usize], p2: &[usize]) -> Perm {
    assert_eq!(p1.len(), p2.len(), "permutations must have the same degree");
    (0..p1.len()).map(|i| p2[p1[i]]).collect()
}

/// Compute the inverse of a permutation.
pub fn inverse(p: &[usize]) -> Perm {
    let mut inv = vec![0; p.len()];
    for (i, image) in p.iter().enumerate() {
        inv[*image] = i;
    }
    inv
}

/// Apply a permutation to a point: return p[point].
pub fn on_points(point: usize, p: &[usize]) -> usize {
    p[point]
}

/// Find all points fixed by the permutation (p[i] == i).
pub fn stable_points(p: &[usize]) -> Vec<usize> {
    p.iter()
        .enumerate()
        .filter_map(|(i, image)| (*image == i).then_some(i))
        .collect()
}

/// Find the first point NOT fixed by the permutation. Returns None if identity.
pub fn first_nonstable_point(p: &[usize]) -> Option<usize> {
    p.iter()
        .enumerate()
        .find_map(|(i, image)| (*image != i).then_some(i))
}

/// Compute the orbit of a point under a set of generators.
/// Returns the set of all points reachable from `point` by applying generators.
pub fn orbit(point: usize, generators: &[Perm]) -> Vec<usize> {
    let n = generators
        .iter()
        .map(|g| g.len())
        .max()
        .unwrap_or(point.saturating_add(1));
    let mut seen = vec![false; n];
    let mut queue = VecDeque::new();
    let inverses: Vec<Perm> = generators.iter().map(|g| inverse(g)).collect();

    if point < n {
        seen[point] = true;
        queue.push_back(point);
    }

    while let Some(current) = queue.pop_front() {
        for generator in generators {
            let next = on_points(current, generator);
            if !seen[next] {
                seen[next] = true;
                queue.push_back(next);
            }
        }
        for generator in &inverses {
            let next = on_points(current, generator);
            if !seen[next] {
                seen[next] = true;
                queue.push_back(next);
            }
        }
    }

    seen.iter()
        .enumerate()
        .filter_map(|(i, reached)| (*reached).then_some(i))
        .collect()
}

/// Compute all orbits of the group generated by `generators` on {0, 1, ..., n-1}.
/// Returns a Vec where orbits[i] is the orbit number of point i.
pub fn all_orbits(generators: &[Perm], n: usize) -> Vec<usize> {
    let mut labels = vec![usize::MAX; n];
    let mut orbit_id = 0usize;
    for point in 0..n {
        if labels[point] != usize::MAX {
            continue;
        }
        for member in orbit(point, generators) {
            labels[member] = orbit_id;
        }
        orbit_id += 1;
    }
    labels
}

fn use_parallel(n: usize, generators: &[Perm]) -> bool {
    n >= 20 && generators.len() >= 4
}

/// Parallel orbit computation. Falls back to `orbit` for small inputs.
pub fn orbit_parallel(point: usize, generators: &[Perm], n: usize) -> Vec<usize> {
    if !use_parallel(n, generators) {
        return orbit(point, generators);
    }
    if point >= n {
        return Vec::new();
    }

    let extended = extended_generators(generators);
    let seen: Vec<AtomicBool> = (0..n).map(|_| AtomicBool::new(false)).collect();
    seen[point].store(true, AtomicOrdering::Relaxed);
    let mut frontier = vec![point];

    while !frontier.is_empty() {
        let mut next = frontier
            .par_iter()
            .flat_map_iter(|current| {
                extended.iter().filter_map(|generator| {
                    let candidate = on_points(*current, generator);
                    (candidate < n
                        && seen[candidate]
                            .compare_exchange(
                                false,
                                true,
                                AtomicOrdering::AcqRel,
                                AtomicOrdering::Acquire,
                            )
                            .is_ok())
                    .then_some(candidate)
                })
            })
            .collect::<Vec<_>>();
        next.sort_unstable();
        next.dedup();
        frontier = next;
    }

    seen.iter()
        .enumerate()
        .filter_map(|(i, reached)| reached.load(AtomicOrdering::Acquire).then_some(i))
        .collect()
}

/// Parallel all-orbits computation using `orbit_parallel` for each component.
pub fn all_orbits_parallel(generators: &[Perm], n: usize) -> Vec<usize> {
    if !use_parallel(n, generators) {
        return all_orbits(generators, n);
    }

    let mut labels = vec![usize::MAX; n];
    let mut orbit_id = 0usize;
    for point in 0..n {
        if labels[point] != usize::MAX {
            continue;
        }
        for member in orbit_parallel(point, generators, n) {
            labels[member] = orbit_id;
        }
        orbit_id += 1;
    }
    labels
}

/// Compute a Schreier vector for `point` under `generators`.
/// Returns (nu, w) where:
/// - nu[i] is the point that maps to i on the path from `point` to i
/// - w[i] is the index of the generator used (or usize::MAX if not reached)
///   Together they encode the path from `point` to any point in its orbit.
pub fn schreier_vector(point: usize, generators: &[Perm], n: usize) -> (Vec<usize>, Vec<usize>) {
    let mut nu = vec![usize::MAX; n];
    let mut w = vec![usize::MAX; n];
    let mut seen = vec![false; n];
    let mut queue = VecDeque::new();

    if point < n {
        seen[point] = true;
        nu[point] = point;
        queue.push_back(point);
    }

    while let Some(current) = queue.pop_front() {
        for (gen_index, generator) in generators.iter().enumerate() {
            let next = on_points(current, generator);
            if !seen[next] {
                seen[next] = true;
                nu[next] = current;
                w[next] = gen_index;
                queue.push_back(next);
            }
        }
    }

    (nu, w)
}

/// Trace back through a Schreier vector to find the group element
/// that maps `point` to `target`. Returns the permutation.
pub fn trace_schreier(
    target: usize,
    point: usize,
    nu: &[usize],
    w: &[usize],
    generators: &[Perm],
    n: usize,
) -> Perm {
    if target >= n || point >= n || nu.get(target).copied().unwrap_or(usize::MAX) == usize::MAX {
        return identity(n);
    }
    let mut current = target;
    let mut trace = identity(n);
    while current != point {
        let gen_index = w[current];
        if gen_index == usize::MAX {
            return identity(n);
        }
        let generator = generators[gen_index].clone();
        trace = product(&generator, &trace);
        current = nu[current];
    }
    trace
}

fn fixes_all(points: &[usize], p: &[usize]) -> bool {
    points.iter().all(|point| p[*point] == *point)
}

fn contains_perm(perms: &[Perm], candidate: &[usize]) -> bool {
    perms.iter().any(|perm| perm == candidate)
}

/// Compute the stabilizer subgroup of a set of points.
/// Given generators of a group G, return generators of Stab_G(points).
pub fn stabilizer(points: &[usize], generators: &[Perm], n: usize) -> Vec<Perm> {
    let mut stabilizer_gens = Vec::new();

    for generator in generators {
        if fixes_all(points, generator) && !contains_perm(&stabilizer_gens, generator) {
            stabilizer_gens.push(generator.clone());
        }
    }

    if points.is_empty() {
        return stabilizer_gens;
    }

    let base = points[0];
    let schreier_gens = extended_generators(generators);
    let (nu, w) = schreier_vector(base, &schreier_gens, n);
    let orbit_points: Vec<usize> = (0..n).filter(|point| nu[*point] != usize::MAX).collect();

    for orbit_point in orbit_points {
        let trace_to_orbit = trace_schreier(orbit_point, base, &nu, &w, &schreier_gens, n);
        for generator in generators {
            let moved = on_points(orbit_point, generator);
            if moved >= n || nu[moved] == usize::MAX {
                continue;
            }
            let trace_to_moved = trace_schreier(moved, base, &nu, &w, &schreier_gens, n);
            let schreier_gen = product(
                &product(&trace_to_orbit, generator),
                &inverse(&trace_to_moved),
            );
            if fixes_all(points, &schreier_gen)
                && !is_identity(&schreier_gen)
                && !contains_perm(&stabilizer_gens, &schreier_gen)
            {
                stabilizer_gens.push(schreier_gen);
            }
        }
    }

    stabilizer_gens
}

/// Parallel stabilizer generator construction. Falls back to `stabilizer` for small inputs.
pub fn stabilizer_parallel(points: &[usize], generators: &[Perm], n: usize) -> Vec<Perm> {
    if !use_parallel(n, generators) {
        return stabilizer(points, generators, n);
    }

    let mut stabilizer_gens: Vec<Perm> = generators
        .par_iter()
        .filter(|generator| fixes_all(points, generator))
        .cloned()
        .collect();
    stabilizer_gens.sort();
    stabilizer_gens.dedup();

    if points.is_empty() {
        return stabilizer_gens;
    }

    let base = points[0];
    let schreier_gens = extended_generators(generators);
    let (nu, w) = schreier_vector(base, &schreier_gens, n);
    let orbit_points: Vec<usize> = (0..n).filter(|point| nu[*point] != usize::MAX).collect();

    let mut candidates: Vec<Perm> = orbit_points
        .par_iter()
        .flat_map_iter(|orbit_point| {
            let trace_to_orbit = trace_schreier(*orbit_point, base, &nu, &w, &schreier_gens, n);
            generators
                .iter()
                .filter_map(|generator| {
                    let moved = on_points(*orbit_point, generator);
                    if moved >= n || nu[moved] == usize::MAX {
                        return None;
                    }
                    let trace_to_moved = trace_schreier(moved, base, &nu, &w, &schreier_gens, n);
                    let schreier_gen = product(
                        &product(&trace_to_orbit, generator),
                        &inverse(&trace_to_moved),
                    );
                    (fixes_all(points, &schreier_gen) && !is_identity(&schreier_gen))
                        .then_some(schreier_gen)
                })
                .collect::<Vec<_>>()
        })
        .collect();

    candidates.sort();
    candidates.dedup();
    for candidate in candidates {
        if !contains_perm(&stabilizer_gens, &candidate) {
            stabilizer_gens.push(candidate);
        }
    }

    stabilizer_gens
}

/// Count the number of inversions in a permutation (for computing sign).
pub fn sign(p: &[usize]) -> i32 {
    let mut inversions = 0usize;
    for i in 0..p.len() {
        for j in (i + 1)..p.len() {
            if p[i] > p[j] {
                inversions += 1;
            }
        }
    }
    if inversions % 2 == 0 {
        1
    } else {
        -1
    }
}

/// Create a transposition: swaps positions i and j, fixes everything else.
pub fn transposition(n: usize, i: usize, j: usize) -> Perm {
    let mut p = identity(n);
    p.swap(i, j);
    p
}

/// Enumerate all elements of the subgroup generated by `generators`.
///
/// The result is sorted lexicographically and always contains the identity element.
/// This is intended for small groups used by higher-level exact algorithms.
pub fn enumerate_subgroup(generators: &[Perm], n: usize) -> Vec<Perm> {
    let mut elements = vec![identity(n)];
    if generators.is_empty() {
        return elements;
    }

    let mut queue = VecDeque::from([identity(n)]);
    let actions = extended_generators(generators);

    while let Some(current) = queue.pop_front() {
        for generator in &actions {
            let next = product(&current, generator);
            if !contains_perm(&elements, &next) {
                elements.push(next.clone());
                queue.push_back(next);
            }
        }
    }

    elements.sort();
    elements.dedup();
    elements
}

fn stabilizer_generators_for_level(base: &[usize], level: usize, generators: &[Perm]) -> Vec<Perm> {
    if level == 0 || generators.is_empty() {
        return generators.to_vec();
    }
    let n = generators.first().map(|g| g.len()).unwrap_or(base.len());
    stabilizer(&base[..level], generators, n)
}

fn extended_generators(generators: &[Perm]) -> Vec<Perm> {
    let mut extended = generators.to_vec();
    for inverse_gen in generators.iter().map(|g| inverse(g)) {
        if !contains_perm(&extended, &inverse_gen) {
            extended.push(inverse_gen);
        }
    }
    extended
}

/// Sift a permutation through the stabilizer chain.
/// Returns true if the permutation is already in the group (sifts to identity).
fn sift(perm: &[usize], base: &[usize], generators: &[Perm], n: usize) -> bool {
    let mut current = perm.to_vec();

    for (level, &bp) in base.iter().enumerate() {
        let img = on_points(bp, &current);
        if img == bp {
            continue;
        }

        let stab_gens = stabilizer_generators_for_level(base, level, generators);
        let schreier_gens = extended_generators(&stab_gens);
        let (nu, w) = schreier_vector(bp, &schreier_gens, n);
        if nu.get(img).copied().unwrap_or(usize::MAX) == usize::MAX {
            return false;
        }

        let rep = trace_schreier(img, bp, &nu, &w, &schreier_gens, n);
        current = product(&current, &inverse(&rep));
    }

    is_identity(&current)
}

/// Compute a Strong Generating Set from generators.
///
/// Input: initial base hint (can be empty), generators, degree n.
/// Output: SGS with a valid base and strong generating set.
pub fn schreier_sims(base_hint: &[usize], generators: &[Perm], n: usize) -> SGS {
    if generators.is_empty() {
        return SGS {
            base: vec![],
            generators: vec![],
            n,
        };
    }

    let mut base: Vec<usize> = base_hint.to_vec();
    let mut strong_gens: Vec<Perm> = generators.to_vec();

    for generator in generators {
        for (i, &img) in generator.iter().enumerate() {
            if img != i && !base.contains(&i) {
                base.push(i);
            }
        }
    }

    let mut seen = std::collections::HashSet::new();
    base.retain(|x| seen.insert(*x));

    let mut changed = true;
    let mut iteration = 0usize;
    let max_iterations = 100usize;

    while changed && iteration < max_iterations {
        changed = false;
        iteration += 1;

        for level in (0..base.len()).rev() {
            let stab_gens = stabilizer_generators_for_level(&base, level, &strong_gens);
            if stab_gens.is_empty() {
                continue;
            }

            let bp = base[level];
            let schreier_gens = extended_generators(&stab_gens);
            let (nu, w) = schreier_vector(bp, &schreier_gens, n);
            let orb = orbit(bp, &stab_gens);

            for &gamma in &orb {
                for generator in &stab_gens {
                    let gen_gamma = on_points(gamma, generator);
                    let trace_gamma = trace_schreier(gamma, bp, &nu, &w, &schreier_gens, n);
                    let trace_gen_gamma = trace_schreier(gen_gamma, bp, &nu, &w, &schreier_gens, n);

                    let schreier_gen = product(
                        &product(&inverse(&trace_gen_gamma), generator),
                        &trace_gamma,
                    );

                    if !is_identity(&schreier_gen)
                        && !contains_perm(&strong_gens, &schreier_gen)
                        && !sift(&schreier_gen, &base, &strong_gens, n)
                    {
                        strong_gens.push(schreier_gen);
                        changed = true;
                    }
                }
            }
        }
    }

    strong_gens.retain(|g| !is_identity(g));
    strong_gens.sort();
    strong_gens.dedup();

    SGS {
        base,
        generators: strong_gens,
        n,
    }
}

/// Parallel Schreier-Sims construction. Level ordering remains sequential; orbit and
/// Schreier generator candidate generation are parallelized within each level.
pub fn schreier_sims_parallel(generators: &[Perm], n: usize) -> SGS {
    if !use_parallel(n, generators) {
        return schreier_sims(&[], generators, n);
    }
    if generators.is_empty() {
        return SGS {
            base: vec![],
            generators: vec![],
            n,
        };
    }

    let mut base: Vec<usize> = Vec::new();
    let mut strong_gens: Vec<Perm> = generators.to_vec();

    for generator in generators {
        for (i, &img) in generator.iter().enumerate() {
            if img != i && !base.contains(&i) {
                base.push(i);
            }
        }
    }

    let mut seen = HashSet::new();
    base.retain(|x| seen.insert(*x));

    let mut changed = true;
    let mut iteration = 0usize;
    let max_iterations = 100usize;

    while changed && iteration < max_iterations {
        changed = false;
        iteration += 1;

        for level in (0..base.len()).rev() {
            let stab_gens = stabilizer_generators_for_level(&base, level, &strong_gens);
            if stab_gens.is_empty() {
                continue;
            }

            let bp = base[level];
            let schreier_gens = extended_generators(&stab_gens);
            let (nu, w) = schreier_vector(bp, &schreier_gens, n);
            let orb = orbit_parallel(bp, &stab_gens, n);

            let mut candidates: Vec<Perm> = orb
                .par_iter()
                .flat_map_iter(|gamma| {
                    stab_gens.iter().filter_map(|generator| {
                        let gen_gamma = on_points(*gamma, generator);
                        let trace_gamma = trace_schreier(*gamma, bp, &nu, &w, &schreier_gens, n);
                        let trace_gen_gamma =
                            trace_schreier(gen_gamma, bp, &nu, &w, &schreier_gens, n);

                        let schreier_gen = product(
                            &product(&inverse(&trace_gen_gamma), generator),
                            &trace_gamma,
                        );
                        (!is_identity(&schreier_gen)).then_some(schreier_gen)
                    })
                })
                .collect();
            candidates.sort();
            candidates.dedup();

            for candidate in candidates {
                if !contains_perm(&strong_gens, &candidate)
                    && !sift(&candidate, &base, &strong_gens, n)
                {
                    strong_gens.push(candidate);
                    changed = true;
                }
            }
        }
    }

    strong_gens.retain(|g| !is_identity(g));
    strong_gens.sort();
    strong_gens.dedup();

    SGS {
        base,
        generators: strong_gens,
        n,
    }
}

/// Test membership in the group.
pub fn is_member(perm: &[usize], sgs: &SGS) -> bool {
    sift(perm, &sgs.base, &sgs.generators, sgs.n)
}

/// Compute the order of the group from its SGS.
pub fn group_order(sgs: &SGS) -> u64 {
    let mut order = 1u64;
    for (level, &bp) in sgs.base.iter().enumerate() {
        let stab_gens = stabilizer_generators_for_level(&sgs.base, level, &sgs.generators);
        let orb = orbit(bp, &stab_gens);
        order *= orb.len() as u64;
    }
    order
}

fn compare_on_free_indices(a: &[usize], b: &[usize], free_indices: &[usize]) -> std::cmp::Ordering {
    for &idx in free_indices {
        if let (Some(lhs), Some(rhs)) = (a.get(idx), b.get(idx)) {
            match lhs.cmp(rhs) {
                std::cmp::Ordering::Equal => {}
                non_eq => return non_eq,
            }
        }
    }
    a.cmp(b)
}

fn choose_better(candidate: Perm, current_best: Option<Perm>, slots: &[usize]) -> Option<Perm> {
    match current_best {
        None => Some(candidate),
        Some(best) => {
            let ordering = if slots.is_empty() {
                candidate.cmp(&best)
            } else {
                compare_on_free_indices(&candidate, &best, slots)
            };
            if ordering == std::cmp::Ordering::Less {
                Some(candidate)
            } else {
                Some(best)
            }
        }
    }
}

/// Compute the coset representative of a permutation relative to a subgroup.
/// Given perm and a group (base, generators), find the unique coset representative
/// cr such that perm = cr * h for some h in the group.
/// The representative is the lexicographically smallest element in the coset.
pub fn coset_representative(perm: &[usize], sgs: &SGS, free_indices: &[usize]) -> Perm {
    coset_rep(perm, sgs.n, &sgs.base, &sgs.generators, free_indices)
}

fn apply_group_action(perm: &[usize], g: &[usize]) -> Perm {
    (0..perm.len()).map(|i| perm[on_points(i, g)]).collect()
}

fn apply_label_action(perm: &[usize], g: &[usize]) -> Perm {
    product(perm, g)
}

fn has_sign_slots(n: usize) -> bool {
    n >= 4
}

/// Find the lexicographically smallest permutation in the orbit of `perm` under the
/// group generated by `sgs`. This is the canonical form.
///
/// Also handles a sign slot: the last two elements of the permutation
/// encode the sign. If they're swapped relative to [n, n+1], the expression
/// picks up a minus sign.
pub fn canonical_perm(perm: &[usize], sgs: &SGS, dummy_pairs: &[(usize, usize)]) -> (Perm, i32) {
    canonical_perm_ext(perm, sgs, dummy_pairs, &[], 1)
}

fn perm_sign_state(perm: &[usize], n: usize) -> i32 {
    if !has_sign_slots(n) {
        return 1;
    }
    let sign_pos = n - 2;
    let sign_neg = n - 1;
    if perm[sign_pos] == sign_neg && perm[sign_neg] == sign_pos {
        -1
    } else {
        1
    }
}

/// Find the coset representative for free indices.
/// Given permutation p, stabilizer chain (base, SGS), and free index slots,
/// find the element s in S such that s·p has the free indices in canonical position.
pub fn coset_rep(
    perm: &[usize],
    n: usize,
    base: &[usize],
    generators: &[Perm],
    free_slots: &[usize],
) -> Perm {
    if generators.is_empty() || free_slots.is_empty() {
        return perm.to_vec();
    }

    fn recurse(
        current: &[usize],
        n: usize,
        base: &[usize],
        generators: &[Perm],
        free_slots: &[usize],
        level: usize,
    ) -> Perm {
        if level >= base.len() {
            return current.to_vec();
        }

        let bp = base[level];
        let level_gens = stabilizer_generators_for_level(base, level, generators);
        if level_gens.is_empty() {
            return recurse(current, n, base, generators, free_slots, level + 1);
        }

        let orbit_points = orbit(bp, &level_gens);
        let min_image = orbit_points
            .iter()
            .map(|&pt| current[pt])
            .min()
            .unwrap_or(current[bp]);

        let ext_gens = extended_generators(&level_gens);
        let (nu, w) = schreier_vector(bp, &ext_gens, n);
        let mut best: Option<Perm> = None;

        for &pt in &orbit_points {
            if current[pt] != min_image {
                continue;
            }
            let rep = trace_schreier(pt, bp, &nu, &w, &ext_gens, n);
            let next = apply_group_action(current, &rep);
            let candidate = recurse(&next, n, base, generators, free_slots, level + 1);
            best = choose_better(candidate, best, free_slots);
        }

        best.unwrap_or_else(|| current.to_vec())
    }

    recurse(perm, n, base, generators, free_slots, 0)
}

fn coset_rep_parallel(
    perm: &[usize],
    n: usize,
    base: &[usize],
    generators: &[Perm],
    free_slots: &[usize],
) -> Perm {
    if generators.is_empty() || free_slots.is_empty() {
        return perm.to_vec();
    }

    fn recurse(
        current: &[usize],
        n: usize,
        base: &[usize],
        generators: &[Perm],
        free_slots: &[usize],
        level: usize,
    ) -> Perm {
        if level >= base.len() {
            return current.to_vec();
        }

        let bp = base[level];
        let level_gens = stabilizer_generators_for_level(base, level, generators);
        if level_gens.is_empty() {
            return recurse(current, n, base, generators, free_slots, level + 1);
        }

        let orbit_points = orbit_parallel(bp, &level_gens, n);
        let min_image = orbit_points
            .iter()
            .map(|&pt| current[pt])
            .min()
            .unwrap_or(current[bp]);
        let candidates: Vec<usize> = orbit_points
            .into_iter()
            .filter(|pt| current[*pt] == min_image)
            .collect();
        let ext_gens = extended_generators(&level_gens);
        let (nu, w) = schreier_vector(bp, &ext_gens, n);

        if candidates.len() > 4 {
            candidates
                .par_iter()
                .map(|pt| {
                    let rep = trace_schreier(*pt, bp, &nu, &w, &ext_gens, n);
                    let next = apply_group_action(current, &rep);
                    recurse(&next, n, base, generators, free_slots, level + 1)
                })
                .reduce_with(
                    |a, b| match choose_better(a.clone(), Some(b.clone()), free_slots) {
                        Some(best) => best,
                        None => a,
                    },
                )
                .unwrap_or_else(|| current.to_vec())
        } else {
            let mut best: Option<Perm> = None;
            for pt in candidates {
                let rep = trace_schreier(pt, bp, &nu, &w, &ext_gens, n);
                let next = apply_group_action(current, &rep);
                let candidate = recurse(&next, n, base, generators, free_slots, level + 1);
                best = choose_better(candidate, best, free_slots);
            }
            best.unwrap_or_else(|| current.to_vec())
        }
    }

    recurse(perm, n, base, generators, free_slots, 0)
}

/// Parallel canonical representative over a symmetry generating set and free slots.
pub fn canonical_perm_parallel(
    tensor_perm: &[usize],
    generating_set: &[Perm],
    freeslots: &[usize],
    n: usize,
) -> (Perm, i32) {
    if !use_parallel(n, generating_set) {
        let sgs = schreier_sims(&[], generating_set, n);
        let result = coset_rep(tensor_perm, n, &sgs.base, &sgs.generators, freeslots);
        let sign = if has_sign_slots(n) && result[n - 2] != n - 2 {
            -1
        } else {
            1
        };
        return (result, sign);
    }

    let sgs = schreier_sims_parallel(generating_set, n);
    let result = coset_rep_parallel(tensor_perm, n, &sgs.base, &sgs.generators, freeslots);
    let sign = if has_sign_slots(n) && result[n - 2] != n - 2 {
        -1
    } else {
        1
    };
    (result, sign)
}

/// Compute generators for the dummy index symmetry group.
pub fn dummy_group_generators(
    dummy_sets: &[DummySet],
    repeated_sets: &[RepeatedSet],
    n: usize,
) -> Vec<Perm> {
    let sign_pos = if has_sign_slots(n) { n - 2 } else { n };
    let sign_neg = if has_sign_slots(n) { n - 1 } else { n };
    let mut gens = Vec::new();

    for dset in dummy_sets {
        match dset.metric_symmetry {
            1 => {
                for &(a, b) in &dset.pairs {
                    let mut g: Perm = (0..n).collect();
                    g.swap(a, b);
                    gens.push(g);
                }
                for i in 0..dset.pairs.len() {
                    for j in (i + 1)..dset.pairs.len() {
                        let (a1, b1) = dset.pairs[i];
                        let (a2, b2) = dset.pairs[j];
                        let mut g: Perm = (0..n).collect();
                        g.swap(a1, a2);
                        g.swap(b1, b2);
                        gens.push(g);
                    }
                }
            }
            -1 => {
                for &(a, b) in &dset.pairs {
                    let mut g: Perm = (0..n).collect();
                    g.swap(a, b);
                    if has_sign_slots(n) {
                        g.swap(sign_pos, sign_neg);
                    }
                    gens.push(g);
                }
                for i in 0..dset.pairs.len() {
                    for j in (i + 1)..dset.pairs.len() {
                        let (a1, b1) = dset.pairs[i];
                        let (a2, b2) = dset.pairs[j];
                        let mut g: Perm = (0..n).collect();
                        g.swap(a1, a2);
                        g.swap(b1, b2);
                        gens.push(g);
                    }
                }
            }
            0 => {
                for i in 0..dset.pairs.len() {
                    for j in (i + 1)..dset.pairs.len() {
                        let (a1, b1) = dset.pairs[i];
                        let (a2, b2) = dset.pairs[j];
                        let mut g: Perm = (0..n).collect();
                        g.swap(a1, a2);
                        g.swap(b1, b2);
                        gens.push(g);
                    }
                }
            }
            _ => {}
        }
    }

    for rset in repeated_sets {
        for i in 0..rset.positions.len().saturating_sub(1) {
            let mut g: Perm = (0..n).collect();
            g.swap(rset.positions[i], rset.positions[i + 1]);
            gens.push(g);
        }
    }

    gens
}

fn project_dummy_sets_to_labels(perm: &[usize], dummy_sets: &[DummySet]) -> Vec<DummySet> {
    dummy_sets
        .iter()
        .map(|set| DummySet {
            pairs: set.pairs.iter().map(|&(a, b)| (perm[a], perm[b])).collect(),
            metric_symmetry: set.metric_symmetry,
        })
        .collect()
}

fn project_repeated_sets_to_labels(
    perm: &[usize],
    repeated_sets: &[RepeatedSet],
) -> Vec<RepeatedSet> {
    repeated_sets
        .iter()
        .map(|set| RepeatedSet {
            positions: set.positions.iter().map(|&p| perm[p]).collect(),
        })
        .collect()
}

fn drop_dummy_index(dummy_sets: &mut [DummySet], first_dummy: usize) {
    for set in dummy_sets {
        if let Some(pos) = set
            .pairs
            .iter()
            .position(|&(first, second)| first == first_dummy || second == first_dummy)
        {
            set.pairs.remove(pos);
            return;
        }
    }
}

fn drop_repeated_index(repeated_sets: &mut [RepeatedSet], first_repeated: usize) {
    for set in repeated_sets {
        if let Some(pos) = set
            .positions
            .iter()
            .position(|&position| position == first_repeated)
        {
            set.positions.remove(pos);
            return;
        }
    }
}

/// Construct the SGS for the dummy group D from dummy sets and repeated sets.
///
/// # Arguments
/// * `dummy_sets` - each set has pairs of index names and a metric_symmetry sign (+1, -1, or 0)
/// * `repeated_sets` - each set has a list of positions of repeated indices
/// * `n` - degree of the permutations
/// * `first_dummy` - if nonzero, rearrange the base of D so that this index comes first
///
/// # Returns
/// `(generators, base)` for group D.
pub fn sgsd(
    dummy_sets: &[DummySet],
    repeated_sets: &[RepeatedSet],
    n: usize,
    first_dummy: usize,
) -> (Vec<Perm>, Vec<usize>) {
    let raw_gens = dummy_group_generators(dummy_sets, repeated_sets, n);
    if raw_gens.is_empty() {
        return (Vec::new(), Vec::new());
    }

    let mut base: Vec<usize> = dummy_sets
        .iter()
        .flat_map(|set| set.pairs.iter().flat_map(|&(a, b)| [a, b]))
        .chain(
            repeated_sets
                .iter()
                .flat_map(|set| set.positions.iter().copied()),
        )
        .filter(|&point| point < n)
        .collect();
    base.sort_unstable();
    base.dedup();
    if first_dummy < n {
        if let Some(pos) = base.iter().position(|&point| point == first_dummy) {
            let point = base.remove(pos);
            base.insert(0, point);
        }
    }

    let sgs = schreier_sims(&base, &raw_gens, n);
    (sgs.generators, sgs.base)
}

/// Compute the F1 set: all possible images of a slot under S·g·D.
///
/// For a given ALPHA entry with accumulated (s, d), the orbit of slot `b` under S
/// gives candidate slots. For each candidate slot, apply g and d to get the
/// current index there, then include all indices in the same D-orbit.
fn f1_images(
    alpha_entry: &AlphaEntry,
    g: &[usize],
    n: usize,
    s_orbit: &[usize],
    d_orbits: &[usize],
) -> Vec<usize> {
    let current = f2(&alpha_entry.s, g, &alpha_entry.d, n);
    let mut images = Vec::new();
    for &slot in s_orbit {
        if slot >= n {
            continue;
        }
        let image = current[slot];
        let orbit_label = d_orbits.get(image).copied().unwrap_or(usize::MAX);
        for point in 0..n {
            if d_orbits.get(point).copied().unwrap_or(usize::MAX) == orbit_label {
                images.push(point);
            }
        }
    }
    images.sort_unstable();
    images.dedup();
    images
}

/// Compose s·g·d and return the resulting permutation.
fn f2(s: &[usize], g: &[usize], d: &[usize], _n: usize) -> Perm {
    apply_label_action(&apply_group_action(g, s), d)
}

/// Check consistency: if any two permutations in the ALPHA level produce
/// the same body but opposite signs, the expression is zero.
fn consistency_check(perms: &[Perm], n: usize, track_sign: bool) -> bool {
    if !track_sign {
        return true;
    }
    for (i, lhs) in perms.iter().enumerate() {
        let lhs_body = if has_sign_slots(n) {
            &lhs[..(n - 2)]
        } else {
            lhs.as_slice()
        };
        let lhs_sign = perm_sign_state(lhs, n);
        for rhs in perms.iter().skip(i + 1) {
            let rhs_body = if has_sign_slots(n) {
                &rhs[..(n - 2)]
            } else {
                rhs.as_slice()
            };
            if lhs_body == rhs_body && lhs_sign != perm_sign_state(rhs, n) {
                return false;
            }
        }
    }
    true
}

/// Sort a list of indices according to a base ordering.
/// `bsort[i]` gives the priority of index `i` in the canonical ordering.
fn sort_by_base(list: &[usize], bsort: &[usize]) -> Vec<usize> {
    let mut sorted = list.to_vec();
    sorted.dedup();
    sorted.sort_by_key(|point| match bsort.iter().position(|base| base == point) {
        Some(priority) => (0usize, priority),
        None => (1usize, *point),
    });
    sorted
}

fn body_slots(n: usize) -> std::ops::Range<usize> {
    0..if has_sign_slots(n) { n - 2 } else { n }
}

fn double_coset_rep_impl(
    perm: &[usize],
    n: usize,
    base: &[usize],
    s_generators: &[Perm],
    dummy_sets: &[DummySet],
    repeated_sets: &[RepeatedSet],
    parallel_next: bool,
) -> (Perm, bool) {
    let initial_label_dummy_sets = project_dummy_sets_to_labels(perm, dummy_sets);
    let initial_label_repeated_sets = project_repeated_sets_to_labels(perm, repeated_sets);
    let first_dummy = initial_label_dummy_sets
        .iter()
        .flat_map(|set| set.pairs.iter().flat_map(|&(a, b)| [a, b]))
        .chain(
            initial_label_repeated_sets
                .iter()
                .flat_map(|set| set.positions.iter().copied()),
        )
        .find(|&point| point < n)
        .unwrap_or(n);
    let (d_generators, _d_base) = sgsd(
        &initial_label_dummy_sets,
        &initial_label_repeated_sets,
        n,
        first_dummy,
    );
    let track_sign = dummy_sets.iter().any(|set| set.metric_symmetry < 0);

    if s_generators.is_empty() && d_generators.is_empty() {
        return (perm.to_vec(), false);
    }

    let mut active_dummy_sets = initial_label_dummy_sets.clone();
    let mut active_repeated_sets = initial_label_repeated_sets.clone();

    let mut drummies: Vec<usize> = initial_label_dummy_sets
        .iter()
        .flat_map(|set| set.pairs.iter().flat_map(|&(a, b)| [a, b]))
        .chain(
            initial_label_repeated_sets
                .iter()
                .flat_map(|set| set.positions.iter().copied()),
        )
        .filter(|&point| point < n)
        .collect();
    drummies.sort_unstable();
    drummies.dedup();

    let inv_perm = inverse(perm);
    let mut drummy_slots: Vec<usize> = drummies
        .iter()
        .filter_map(|&point| inv_perm.get(point).copied())
        .collect();
    drummy_slots.sort_unstable();
    drummy_slots.dedup();

    let mut b_s: Vec<usize> = base
        .iter()
        .copied()
        .filter(|point| drummy_slots.contains(point))
        .collect();
    let mut base_seen = b_s.clone();
    base_seen.sort_unstable();
    let mut missing_slots: Vec<usize> = drummy_slots
        .iter()
        .copied()
        .filter(|point| !base_seen.contains(point))
        .collect();
    missing_slots.sort_unstable();
    b_s.extend(missing_slots);
    if b_s.is_empty() {
        b_s.extend(body_slots(n));
    }

    let mut sorted_b_s = b_s.clone();
    sorted_b_s.sort_unstable();
    let b_s_sort: Vec<usize> = b_s
        .iter()
        .filter_map(|slot| {
            sorted_b_s
                .iter()
                .position(|sorted_slot| sorted_slot == slot)
                .and_then(|pos| drummies.get(pos).copied())
        })
        .collect();

    let mut alpha = vec![AlphaEntry {
        l: Vec::new(),
        s: identity(n),
        d: identity(n),
        children: vec![None; n],
    }];
    let mut level_indices = vec![0usize];

    for (level, &b) in b_s.iter().enumerate() {
        let s_level_gens = stabilizer_generators_for_level(&b_s, level, s_generators);
        let s_trace_gens = extended_generators(&s_level_gens);
        let (s_nu, s_w) = schreier_vector(b, &s_trace_gens, n);
        let s_orbit: Vec<usize> = if s_level_gens.is_empty() {
            vec![b]
        } else {
            (0..n).filter(|&point| s_nu[point] != usize::MAX).collect()
        };

        let (current_d_gens, _) = sgsd(&active_dummy_sets, &active_repeated_sets, n, 0);
        let d_orbits = all_orbits(&current_d_gens, n);

        let f1: Vec<usize> = level_indices
            .iter()
            .flat_map(|&entry_index| f1_images(&alpha[entry_index], perm, n, &s_orbit, &d_orbits))
            .collect();
        let sorted_f1 = sort_by_base(&f1, &b_s_sort);
        let Some(&chosen_image) = sorted_f1.first() else {
            continue;
        };

        let active_d_empty = active_dummy_sets.iter().all(|set| set.pairs.is_empty())
            && active_repeated_sets
                .iter()
                .all(|set| set.positions.is_empty());
        let d_chosen_gens = if active_d_empty {
            Vec::new()
        } else {
            let (gens, _) = sgsd(&active_dummy_sets, &active_repeated_sets, n, chosen_image);
            gens
        };
        let d_chosen_trace_gens = extended_generators(&d_chosen_gens);
        let (d_nu, d_w) = schreier_vector(chosen_image, &d_chosen_trace_gens, n);
        let d_orbit_chosen: Vec<usize> = if d_chosen_gens.is_empty() {
            vec![chosen_image]
        } else {
            orbit(chosen_image, &d_chosen_gens)
        };

        let next_entries: Vec<(usize, usize, AlphaEntry)> = level_indices
            .iter()
            .flat_map(|&entry_index| {
                let entry = &alpha[entry_index];
                let slots_from_s: Vec<usize> = s_orbit
                    .iter()
                    .filter_map(|&slot| entry.s.get(slot).copied())
                    .collect();
                let gd = product(perm, &entry.d);
                let inv_gd = inverse(&gd);
                let slots_from_d: Vec<usize> = d_orbit_chosen
                    .iter()
                    .filter_map(|&point| inv_gd.get(point).copied())
                    .collect();
                let mut next_slots: Vec<usize> = slots_from_s
                    .iter()
                    .copied()
                    .filter(|slot| slots_from_d.contains(slot))
                    .collect();
                next_slots.sort_unstable();
                next_slots.dedup();

                let build_entry = |slot: usize| {
                    let inv_s = inverse(&entry.s);
                    let s_target = inv_s.get(slot).copied().unwrap_or(slot);
                    let s_trace = trace_schreier(s_target, b, &s_nu, &s_w, &s_trace_gens, n);
                    let gd_image = gd.get(slot).copied().unwrap_or(slot);
                    let d_trace = trace_schreier(
                        gd_image,
                        chosen_image,
                        &d_nu,
                        &d_w,
                        &d_chosen_trace_gens,
                        n,
                    );
                    let inv_d_trace = inverse(&d_trace);
                    let mut l = entry.l.clone();
                    l.push(slot);
                    (
                        entry_index,
                        slot,
                        AlphaEntry {
                            l,
                            s: product(&s_trace, &entry.s),
                            d: product(&entry.d, &inv_d_trace),
                            children: vec![None; n],
                        },
                    )
                };

                if parallel_next && next_slots.len() > 4 {
                    next_slots
                        .into_par_iter()
                        .map(build_entry)
                        .collect::<Vec<_>>()
                } else {
                    next_slots.into_iter().map(build_entry).collect::<Vec<_>>()
                }
            })
            .collect();

        let start = alpha.len();
        for (offset, (parent, slot, child)) in next_entries.into_iter().enumerate() {
            let child_index = start + offset;
            if let Some(parent_entry) = alpha.get_mut(parent) {
                if let Some(child_slot) = parent_entry.children.get_mut(slot) {
                    *child_slot = Some(child_index);
                }
            }
            alpha.push(child);
        }
        level_indices = (start..alpha.len()).collect();

        let level_perms: Vec<Perm> = level_indices
            .iter()
            .map(|&entry_index| f2(&alpha[entry_index].s, perm, &alpha[entry_index].d, n))
            .collect();
        if !consistency_check(&level_perms, n, track_sign) {
            return (vec![0; n], true);
        }

        if level_indices.is_empty() {
            break;
        }

        drop_dummy_index(&mut active_dummy_sets, chosen_image);
        drop_repeated_index(&mut active_repeated_sets, chosen_image);
    }

    let mut best: Option<Perm> = None;
    for entry_index in level_indices {
        let candidate = f2(&alpha[entry_index].s, perm, &alpha[entry_index].d, n);
        best = choose_better(candidate, best, &[]);
    }
    (best.unwrap_or_else(|| perm.to_vec()), false)
}

/// Find the canonical representative of the double coset S·g·D.
pub fn double_coset_rep(
    perm: &[usize],
    n: usize,
    base: &[usize],
    s_generators: &[Perm],
    dummy_sets: &[DummySet],
    repeated_sets: &[RepeatedSet],
) -> (Perm, bool) {
    double_coset_rep_impl(
        perm,
        n,
        base,
        s_generators,
        dummy_sets,
        repeated_sets,
        false,
    )
}

/// Parallel representative for a double coset. This keeps the Schreier-vector
/// traversal sequential by level and parallelizes ALPHA NEXT expansion when useful.
pub fn double_coset_rep_parallel(
    perm: &[usize],
    n: usize,
    base: &[usize],
    s_generators: &[Perm],
    dummy_sets: &[DummySet],
    repeated_sets: &[RepeatedSet],
) -> (Perm, bool) {
    if !use_parallel(n, s_generators) {
        double_coset_rep(perm, n, base, s_generators, dummy_sets, repeated_sets)
    } else {
        double_coset_rep_impl(perm, n, base, s_generators, dummy_sets, repeated_sets, true)
    }
}

/// Extended canonical permutation with full dummy handling.
pub fn canonical_perm_ext(
    perm: &[usize],
    sgs: &SGS,
    dummy_pairs: &[(usize, usize)],
    repeated_sets: &[RepeatedSet],
    metric_symmetry: i32,
) -> (Perm, i32) {
    let dummy_sets = if dummy_pairs.is_empty() {
        Vec::new()
    } else {
        vec![DummySet {
            pairs: dummy_pairs.to_vec(),
            metric_symmetry,
        }]
    };
    canonical_perm_with_sets(perm, sgs, &dummy_sets, repeated_sets)
}

/// Extended canonical permutation with multiple dummy sets and repeated-index sets.
pub fn canonical_perm_with_sets(
    perm: &[usize],
    sgs: &SGS,
    dummy_sets: &[DummySet],
    repeated_sets: &[RepeatedSet],
) -> (Perm, i32) {
    let n = sgs.n;
    if sgs.generators.is_empty() && dummy_sets.is_empty() && repeated_sets.is_empty() {
        return (perm.to_vec(), 1);
    }

    let sign_pos = if has_sign_slots(n) { n - 2 } else { n };
    let dummy_slot_set: HashSet<usize> = dummy_sets
        .iter()
        .flat_map(|set| set.pairs.iter().flat_map(|&(a, b)| [a, b]))
        .collect();
    let repeated_slot_set: HashSet<usize> = repeated_sets
        .iter()
        .flat_map(|set| set.positions.iter().copied())
        .collect();
    let free_slots: Vec<usize> = (0..sign_pos)
        .filter(|i| !dummy_slot_set.contains(i) && !repeated_slot_set.contains(i))
        .collect();

    let after_free = coset_rep(perm, n, &sgs.base, &sgs.generators, &free_slots);

    if dummy_sets.is_empty() && repeated_sets.is_empty() {
        let sign = if has_sign_slots(n) && after_free[sign_pos] != sign_pos {
            -1
        } else {
            1
        };
        return (after_free, sign);
    }

    let mut s_gens = sgs.generators.clone();
    for &slot in &free_slots {
        s_gens = stabilizer(&[slot], &s_gens, n);
    }

    let dummy_base: Vec<usize> = sgs
        .base
        .iter()
        .filter(|b| !free_slots.contains(b))
        .copied()
        .collect();

    let (result, is_zero) = double_coset_rep(
        &after_free,
        n,
        &dummy_base,
        &s_gens,
        dummy_sets,
        repeated_sets,
    );

    if is_zero {
        return (vec![0usize; n], 0);
    }

    let sign = if has_sign_slots(n) && result[sign_pos] != sign_pos {
        -1
    } else {
        1
    };
    (result, sign)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn all_permutations(n: usize) -> Vec<Perm> {
        fn rec(start: usize, data: &mut Vec<usize>, out: &mut Vec<Perm>) {
            if start == data.len() {
                out.push(data.clone());
                return;
            }
            for i in start..data.len() {
                data.swap(start, i);
                rec(start + 1, data, out);
                data.swap(start, i);
            }
        }

        let mut seed: Vec<usize> = (0..n).collect();
        let mut out = Vec::new();
        rec(0, &mut seed, &mut out);
        out
    }

    fn valid_sign_slot_permutations(n: usize) -> Vec<Perm> {
        if !has_sign_slots(n) {
            return all_permutations(n);
        }
        let body_len = n - 2;
        all_permutations(body_len)
            .into_iter()
            .flat_map(|body| {
                let mut positive = body.clone();
                positive.extend([n - 2, n - 1]);
                let mut negative = body;
                negative.extend([n - 1, n - 2]);
                [positive, negative]
            })
            .collect()
    }

    fn brute_force_double_coset(
        perm: &[usize],
        sgs: &SGS,
        dummy_sets: &[DummySet],
        repeated_sets: &[RepeatedSet],
    ) -> (Perm, i32) {
        let n = sgs.n;
        let sign_pos = if has_sign_slots(n) { n - 2 } else { n };
        let dummy_slot_set: HashSet<usize> = dummy_sets
            .iter()
            .flat_map(|set| set.pairs.iter().flat_map(|&(a, b)| [a, b]))
            .collect();
        let repeated_slot_set: HashSet<usize> = repeated_sets
            .iter()
            .flat_map(|set| set.positions.iter().copied())
            .collect();
        let free_slots: Vec<usize> = (0..sign_pos)
            .filter(|i| !dummy_slot_set.contains(i) && !repeated_slot_set.contains(i))
            .collect();

        let after_free = {
            let mut best = perm.to_vec();
            if !free_slots.is_empty() {
                let s_group = all_permutations(n)
                    .into_iter()
                    .filter(|candidate| is_member(candidate, sgs));
                for s in s_group {
                    let candidate = apply_group_action(perm, &s);
                    if compare_on_free_indices(&candidate, &best, &free_slots)
                        == std::cmp::Ordering::Less
                    {
                        best = candidate;
                    }
                }
            }
            best
        };

        let mut s_gens = sgs.generators.clone();
        for &slot in &free_slots {
            s_gens = stabilizer(&[slot], &s_gens, n);
        }

        let s_sgs = if s_gens.is_empty() {
            SGS {
                base: vec![],
                generators: vec![],
                n,
            }
        } else {
            schreier_sims(&[], &s_gens, n)
        };

        let label_dummy_sets = project_dummy_sets_to_labels(&after_free, dummy_sets);
        let label_repeated_sets = project_repeated_sets_to_labels(&after_free, repeated_sets);
        let d_gens = dummy_group_generators(&label_dummy_sets, &label_repeated_sets, n);
        let d_sgs = if d_gens.is_empty() {
            SGS {
                base: vec![],
                generators: vec![],
                n,
            }
        } else {
            schreier_sims(&[], &d_gens, n)
        };

        let mut best: Option<Perm> = None;
        let mut sign_by_body: Vec<(Vec<usize>, i32)> = Vec::new();
        for s in all_permutations(n)
            .into_iter()
            .filter(|candidate| is_member(candidate, &s_sgs))
        {
            for d in all_permutations(n)
                .into_iter()
                .filter(|candidate| is_member(candidate, &d_sgs))
            {
                let candidate = f2(&s, &after_free, &d, n);
                let body = if has_sign_slots(n) {
                    candidate[..(n - 2)].to_vec()
                } else {
                    candidate.clone()
                };
                let sign = perm_sign_state(&candidate, n);
                if let Some((_, prev_sign)) = sign_by_body
                    .iter()
                    .find(|(seen_body, _)| seen_body == &body)
                {
                    if *prev_sign != sign {
                        return (vec![0usize; n], 0);
                    }
                } else {
                    sign_by_body.push((body, sign));
                }
                best = choose_better(candidate, best, &[]);
            }
        }

        let best = best.unwrap_or_else(|| after_free.clone());
        let sign = if has_sign_slots(n) && best[n - 2] != n - 2 {
            -1
        } else {
            1
        };
        (best, sign)
    }

    fn assert_matches_oracle(
        perm: &[usize],
        sgs: &SGS,
        dummy_sets: &[DummySet],
        repeated_sets: &[RepeatedSet],
    ) {
        let actual = canonical_perm_with_sets(perm, sgs, dummy_sets, repeated_sets);
        let oracle = brute_force_double_coset(perm, sgs, dummy_sets, repeated_sets);
        assert_eq!(
            actual, oracle,
            "perm={perm:?} dummy_sets={dummy_sets:?} repeated_sets={repeated_sets:?}"
        );
    }

    fn fixed_large_generators(n: usize) -> Vec<Perm> {
        vec![
            transposition(n, 0, 1),
            transposition(n, 1, 2),
            transposition(n, 3, 4),
            transposition(n, 5, 6),
        ]
    }

    #[test]
    fn test_orbit_parallel_matches_sequential() {
        let n = 30;
        let generators = fixed_large_generators(n);

        let mut sequential = orbit(0, &generators);
        let mut parallel = orbit_parallel(0, &generators, n);
        sequential.sort_unstable();
        parallel.sort_unstable();

        assert_eq!(parallel, sequential);
    }

    #[test]
    fn test_schreier_sims_parallel_matches_sequential() {
        let n = 30;
        let generators = fixed_large_generators(n);

        let sequential = schreier_sims(&[], &generators, n);
        let parallel = schreier_sims_parallel(&generators, n);

        assert_eq!(group_order(&parallel), group_order(&sequential));
    }

    #[test]
    fn test_canonical_perm_parallel_matches_sequential() {
        let n = 30;
        let generators = fixed_large_generators(n);
        let tensor_perm = {
            let mut perm = identity(n);
            perm.swap(0, 2);
            perm.swap(3, 4);
            perm
        };
        let free_slots = vec![0, 1, 2, 3, 4, 5, 6];

        let sgs = schreier_sims(&[], &generators, n);
        let sequential_perm = coset_rep(&tensor_perm, n, &sgs.base, &sgs.generators, &free_slots);
        let sequential_sign = if has_sign_slots(n) && sequential_perm[n - 2] != n - 2 {
            -1
        } else {
            1
        };
        let parallel = canonical_perm_parallel(&tensor_perm, &generators, &free_slots, n);

        assert_eq!(parallel, (sequential_perm, sequential_sign));
    }

    #[test]
    fn identity_is_identity() {
        let id = identity(5);
        assert!(is_identity(&id));
    }

    #[test]
    fn product_with_identity() {
        let id = identity(4);
        let p = vec![1, 0, 3, 2];
        assert_eq!(product(&p, &id), p);
        assert_eq!(product(&id, &p), p);
    }

    #[test]
    fn inverse_undoes() {
        let p = vec![1, 2, 0, 3];
        let ip = inverse(&p);
        let result = product(&p, &ip);
        assert!(is_identity(&result));
    }

    #[test]
    fn orbit_of_cycle() {
        let gen = vec![vec![1, 2, 0, 3]];
        let orb = orbit(0, &gen);
        assert_eq!(orb.len(), 3);
        assert!(orb.contains(&0));
        assert!(orb.contains(&1));
        assert!(orb.contains(&2));
    }

    #[test]
    fn sign_of_transposition() {
        let p = transposition(4, 0, 1);
        assert_eq!(sign(&p), -1);
    }

    #[test]
    fn sign_of_identity() {
        assert_eq!(sign(&identity(5)), 1);
    }

    #[test]
    fn sign_of_3cycle() {
        let p = vec![1, 2, 0, 3];
        assert_eq!(sign(&p), 1);
    }

    #[test]
    fn stabilizer_of_point() {
        let gens = vec![vec![1, 0, 2], vec![0, 2, 1]];
        let stab = stabilizer(&[0], &gens, 3);
        for g in &stab {
            assert_eq!(g[0], 0, "stabilizer element doesn't fix 0: {:?}", g);
        }
    }

    #[test]
    fn sgs_of_s3() {
        let gens = vec![vec![1, 0, 2], vec![0, 2, 1]];
        let sgs = schreier_sims(&[], &gens, 3);
        assert_eq!(group_order(&sgs), 6);
    }

    #[test]
    fn sgs_of_z2() {
        let gens = vec![vec![1, 0]];
        let sgs = schreier_sims(&[], &gens, 2);
        assert_eq!(group_order(&sgs), 2);
    }

    #[test]
    fn sgs_of_s4() {
        let gens = vec![vec![1, 0, 2, 3], vec![0, 2, 1, 3], vec![0, 1, 3, 2]];
        let sgs = schreier_sims(&[], &gens, 4);
        assert_eq!(group_order(&sgs), 24);
    }

    #[test]
    fn membership_test() {
        let gens = vec![vec![1, 0, 2], vec![0, 2, 1]];
        let sgs = schreier_sims(&[], &gens, 3);

        let perm = vec![2, 0, 1];
        assert!(is_member(&perm, &sgs));
        assert!(is_member(&identity(3), &sgs));
    }

    #[test]
    fn membership_test_dummy_sgs_product() {
        let gens = vec![
            vec![3, 1, 2, 0, 4, 5],
            vec![0, 2, 1, 3, 4, 5],
            vec![2, 3, 0, 1, 4, 5],
        ];
        let sgs = schreier_sims(&[], &gens, 6);
        assert!(is_member(&[1, 3, 0, 2, 4, 5], &sgs));
    }

    #[test]
    fn empty_group() {
        let sgs = schreier_sims(&[], &[], 3);
        assert_eq!(group_order(&sgs), 1);
    }

    #[test]
    fn canonical_perm_symmetric_tensor() {
        let gens = vec![vec![1, 0]];
        let sgs = schreier_sims(&[0], &gens, 2);

        let (canon, sign) = canonical_perm(&[1, 0], &sgs, &[]);
        assert_eq!(canon, vec![0, 1]);
        assert_eq!(sign, 1);
    }

    #[test]
    fn canonical_perm_antisymmetric_tensor() {
        let gens = vec![vec![1, 0, 3, 2]];
        let sgs = schreier_sims(&[0], &gens, 4);

        let (canon, _s) = canonical_perm(&[1, 0, 2, 3], &sgs, &[]);
        assert!(canon[0] <= canon[1] || (canon[0] == 0 && canon[1] == 1));
    }

    #[test]
    fn double_coset_symmetric_metric() {
        let gens = vec![
            vec![1, 0, 2, 3, 4, 5],
            vec![0, 1, 3, 2, 4, 5],
            vec![2, 3, 0, 1, 4, 5],
        ];
        let sgs = schreier_sims(&[], &gens, 6);

        let perm = vec![1, 0, 3, 2, 4, 5];
        let dummy_pairs = vec![(0, 2), (1, 3)];
        let (canon, sign) = canonical_perm_ext(&perm, &sgs, &dummy_pairs, &[], 1);

        assert_eq!(canon.len(), 6);
        assert_ne!(sign, 0);
    }

    #[test]
    fn double_coset_symmetric_metric_basic() {
        let n = 4;
        let sgs = schreier_sims(
            &[0, 1, 2, 3],
            &[vec![1, 0, 2, 3], vec![0, 1, 3, 2], vec![2, 3, 0, 1]],
            n,
        );
        let dummy_sets = vec![DummySet {
            pairs: vec![(0, 1), (2, 3)],
            metric_symmetry: 1,
        }];
        let (result, is_zero) = double_coset_rep(
            &[0, 1, 2, 3],
            n,
            &sgs.base,
            &sgs.generators,
            &dummy_sets,
            &[],
        );
        assert!(!is_zero);
        assert_eq!(result.len(), n);
    }

    #[test]
    fn double_coset_antisymmetric_kills_symmetric_tensor() {
        let n = 4;
        let sgs = schreier_sims(&[0, 1], &[vec![1, 0, 2, 3]], n);
        let dummy_sets = vec![DummySet {
            pairs: vec![(0, 1)],
            metric_symmetry: -1,
        }];
        let (_, is_zero) = double_coset_rep(
            &[0, 1, 2, 3],
            n,
            &sgs.base,
            &sgs.generators,
            &dummy_sets,
            &[],
        );
        assert!(is_zero);
    }

    #[test]
    fn double_coset_repeated_indices() {
        let n = 3;
        let sgs = SGS {
            base: vec![],
            generators: vec![],
            n,
        };
        let repeated = vec![RepeatedSet {
            positions: vec![0, 1, 2],
        }];
        let (result, is_zero) =
            double_coset_rep(&[2, 0, 1], n, &sgs.base, &sgs.generators, &[], &repeated);
        assert!(!is_zero);
        assert_eq!(result, vec![0, 1, 2]);
    }

    #[test]
    fn double_coset_riemann_4_dummies() {
        let n = 8;
        let gens = vec![
            vec![1, 0, 2, 3, 4, 5, 6, 7],
            vec![0, 1, 3, 2, 4, 5, 6, 7],
            vec![2, 3, 0, 1, 4, 5, 6, 7],
            vec![0, 1, 2, 3, 5, 4, 6, 7],
            vec![0, 1, 2, 3, 4, 5, 7, 6],
            vec![0, 1, 2, 3, 6, 7, 4, 5],
        ];
        let sgs = schreier_sims(&[0, 1, 2, 3, 4, 5, 6, 7], &gens, n);
        let dummy_sets = vec![DummySet {
            pairs: vec![(0, 4), (1, 5), (2, 6), (3, 7)],
            metric_symmetry: 1,
        }];
        let (result, is_zero) = double_coset_rep(
            &[3, 2, 1, 0, 7, 6, 5, 4],
            n,
            &sgs.base,
            &sgs.generators,
            &dummy_sets,
            &[],
        );
        assert!(!is_zero);
        assert_eq!(result.len(), n);
    }

    #[test]
    fn double_coset_riemann_12_slots_benchmark_shape() {
        let n = 12;
        let mut gens = Vec::new();
        for offset in [0usize, 4, 8] {
            gens.push(transposition(n, offset, offset + 1));
            gens.push(transposition(n, offset + 2, offset + 3));
            let mut pair_exchange = identity(n);
            pair_exchange.swap(offset, offset + 2);
            pair_exchange.swap(offset + 1, offset + 3);
            gens.push(pair_exchange);
        }
        let sgs = schreier_sims(&(0..n).collect::<Vec<_>>(), &gens, n);
        let dummy_sets = vec![DummySet {
            pairs: vec![(0, 4), (1, 5), (2, 8), (3, 9), (6, 10), (7, 11)],
            metric_symmetry: 1,
        }];
        let perm = vec![3, 2, 1, 0, 7, 6, 5, 4, 11, 10, 9, 8];

        let started = std::time::Instant::now();
        let (result, is_zero) =
            double_coset_rep(&perm, n, &sgs.base, &sgs.generators, &dummy_sets, &[]);

        assert!(!is_zero);
        assert_eq!(result.len(), n);
        if !cfg!(debug_assertions) {
            assert!(
                started.elapsed() < std::time::Duration::from_secs(1),
                "12-slot Riemann double-coset canonicalisation exceeded 1s"
            );
        }
    }

    #[test]
    fn double_coset_multiple_dummy_sets() {
        let n = 6;
        let dummy_sets = vec![
            DummySet {
                pairs: vec![(0, 1)],
                metric_symmetry: 1,
            },
            DummySet {
                pairs: vec![(2, 3)],
                metric_symmetry: -1,
            },
        ];
        let (result, is_zero) =
            double_coset_rep(&[0, 1, 2, 3, 4, 5], n, &[], &[], &dummy_sets, &[]);
        assert!(!is_zero);
        assert_eq!(result.len(), n);
    }

    #[test]
    fn repeated_indices_generate_symmetric_dummy_group() {
        let perm = vec![2, 1, 0, 3, 4];
        let sgs = schreier_sims(&[], &[], 5);
        let repeated_sets = vec![RepeatedSet {
            positions: vec![0, 1, 2],
        }];

        let (canon, sign) = canonical_perm_with_sets(&perm, &sgs, &[], &repeated_sets);
        assert_eq!(canon[..3], [0, 1, 2]);
        assert_eq!(sign, 1);
    }

    #[test]
    fn dummy_group_acts_on_labels_not_slots() {
        let perm = vec![2, 3, 0, 1, 4, 5];
        let sgs = schreier_sims(&[], &[], 6);
        let dummy_sets = vec![DummySet {
            pairs: vec![(0, 2), (1, 3)],
            metric_symmetry: 1,
        }];

        let (canon, sign) = canonical_perm_with_sets(&perm, &sgs, &dummy_sets, &[]);
        assert_eq!(canon, vec![0, 1, 2, 3, 4, 5]);
        assert_eq!(sign, 1);
    }

    #[test]
    fn oracle_symmetric_metric_case() {
        let gens = vec![
            vec![1, 0, 2, 3, 4, 5],
            vec![0, 1, 3, 2, 4, 5],
            vec![2, 3, 0, 1, 4, 5],
        ];
        let sgs = schreier_sims(&[], &gens, 6);
        let dummy_sets = vec![DummySet {
            pairs: vec![(0, 2), (1, 3)],
            metric_symmetry: 1,
        }];
        assert_matches_oracle(&[1, 0, 3, 2, 4, 5], &sgs, &dummy_sets, &[]);
    }

    #[test]
    fn oracle_antisymmetric_metric_case() {
        let gens = vec![
            vec![1, 0, 2, 3, 5, 4],
            vec![0, 1, 3, 2, 5, 4],
            vec![2, 3, 0, 1, 4, 5],
        ];
        let sgs = schreier_sims(&[], &gens, 6);
        let dummy_sets = vec![DummySet {
            pairs: vec![(0, 2), (1, 3)],
            metric_symmetry: -1,
        }];
        assert_matches_oracle(&[1, 0, 3, 2, 4, 5], &sgs, &dummy_sets, &[]);
    }

    #[test]
    fn oracle_mixed_dummy_sets_and_repeated_indices() {
        let gens = vec![
            vec![1, 0, 2, 3, 4, 5, 6, 7],
            vec![0, 1, 3, 2, 4, 5, 6, 7],
            vec![0, 1, 2, 3, 5, 4, 6, 7],
        ];
        let sgs = schreier_sims(&[], &gens, 8);
        let dummy_sets = vec![
            DummySet {
                pairs: vec![(0, 2)],
                metric_symmetry: 1,
            },
            DummySet {
                pairs: vec![(1, 3)],
                metric_symmetry: -1,
            },
        ];
        let repeated_sets = vec![RepeatedSet {
            positions: vec![4, 5],
        }];
        assert_matches_oracle(&[2, 3, 0, 1, 5, 4, 6, 7], &sgs, &dummy_sets, &repeated_sets);
    }

    #[test]
    fn exhaustive_oracle_symmetric_metric_degree_6() {
        let gens = vec![
            vec![1, 0, 2, 3, 4, 5],
            vec![0, 1, 3, 2, 4, 5],
            vec![2, 3, 0, 1, 4, 5],
        ];
        let sgs = schreier_sims(&[], &gens, 6);
        let dummy_sets = vec![DummySet {
            pairs: vec![(0, 2), (1, 3)],
            metric_symmetry: 1,
        }];

        for perm in valid_sign_slot_permutations(6).into_iter().take(24) {
            assert_matches_oracle(&perm, &sgs, &dummy_sets, &[]);
        }
    }

    #[test]
    fn exhaustive_oracle_antisymmetric_metric_degree_6() {
        let gens = vec![
            vec![1, 0, 2, 3, 5, 4],
            vec![0, 1, 3, 2, 5, 4],
            vec![2, 3, 0, 1, 4, 5],
        ];
        let sgs = schreier_sims(&[], &gens, 6);
        let dummy_sets = vec![DummySet {
            pairs: vec![(0, 2), (1, 3)],
            metric_symmetry: -1,
        }];

        for perm in valid_sign_slot_permutations(6).into_iter().take(24) {
            assert_matches_oracle(&perm, &sgs, &dummy_sets, &[]);
        }
    }

    #[test]
    fn exhaustive_oracle_repeated_indices_degree_5() {
        let sgs = schreier_sims(&[], &[], 5);
        let repeated_sets = vec![RepeatedSet {
            positions: vec![0, 1, 2],
        }];

        for perm in all_permutations(5).into_iter().take(24) {
            assert_matches_oracle(&perm, &sgs, &[], &repeated_sets);
        }
    }

    #[test]
    fn enumerate_subgroup_of_single_transposition() {
        let generators = vec![transposition(2, 0, 1)];
        let elements = enumerate_subgroup(&generators, 2);
        assert_eq!(elements, vec![vec![0, 1], vec![1, 0]]);
    }
}
