#![forbid(unsafe_code)]

use std::collections::VecDeque;

/// A permutation in images notation. p[i] = image of i under the permutation.
/// Indices are 0-based internally. The identity permutation of degree n is [0, 1, 2, ..., n-1].
pub type Perm = Vec<usize>;

/// Create the identity permutation of degree n.
pub fn identity(n: usize) -> Perm {
    (0..n).collect()
}

/// Check if a permutation is the identity.
pub fn is_identity(p: &[usize]) -> bool {
    p.iter().enumerate().all(|(i, image)| *image == i)
}

/// Compute the product (composition) of two permutations: result[i] = p2[p1[i]].
/// Both must have the same degree.
pub fn product(p1: &[usize], p2: &[usize]) -> Perm {
    assert_eq!(p1.len(), p2.len(), "permutations must have the same degree");
    (0..p1.len()).map(|i| p2[p1[i]]).collect()
}

/// Compute the inverse of a permutation.
pub fn inverse(p: &[usize]) -> Perm {
    let mut inv = vec![0; p.len()];
    for (i, image) in p.iter().enumerate() {
        inv[*image] = i;
    }
    inv
}

/// Apply a permutation to a point: return p[point].
pub fn on_points(point: usize, p: &[usize]) -> usize {
    p[point]
}

/// Find all points fixed by the permutation (p[i] == i).
pub fn stable_points(p: &[usize]) -> Vec<usize> {
    p.iter()
        .enumerate()
        .filter_map(|(i, image)| (*image == i).then_some(i))
        .collect()
}

/// Find the first point NOT fixed by the permutation. Returns None if identity.
pub fn first_nonstable_point(p: &[usize]) -> Option<usize> {
    p.iter()
        .enumerate()
        .find_map(|(i, image)| (*image != i).then_some(i))
}

/// Compute the orbit of a point under a set of generators.
/// Returns the set of all points reachable from `point` by applying generators.
pub fn orbit(point: usize, generators: &[Perm]) -> Vec<usize> {
    let n = generators
        .iter()
        .map(|g| g.len())
        .max()
        .unwrap_or(point.saturating_add(1));
    let mut seen = vec![false; n];
    let mut queue = VecDeque::new();
    let inverses: Vec<Perm> = generators.iter().map(|g| inverse(g)).collect();

    if point < n {
        seen[point] = true;
        queue.push_back(point);
    }

    while let Some(current) = queue.pop_front() {
        for generator in generators {
            let next = on_points(current, generator);
            if !seen[next] {
                seen[next] = true;
                queue.push_back(next);
            }
        }
        for generator in &inverses {
            let next = on_points(current, generator);
            if !seen[next] {
                seen[next] = true;
                queue.push_back(next);
            }
        }
    }

    seen.iter()
        .enumerate()
        .filter_map(|(i, reached)| (*reached).then_some(i))
        .collect()
}

/// Compute all orbits of the group generated by `generators` on {0, 1, ..., n-1}.
/// Returns a Vec where orbits[i] is the orbit number of point i.
pub fn all_orbits(generators: &[Perm], n: usize) -> Vec<usize> {
    let mut labels = vec![usize::MAX; n];
    let mut orbit_id = 0usize;
    for point in 0..n {
        if labels[point] != usize::MAX {
            continue;
        }
        for member in orbit(point, generators) {
            labels[member] = orbit_id;
        }
        orbit_id += 1;
    }
    labels
}

/// Compute a Schreier vector for `point` under `generators`.
/// Returns (nu, w) where:
/// - nu[i] is the point that maps to i on the path from `point` to i
/// - w[i] is the index of the generator used (or usize::MAX if not reached)
/// Together they encode the path from `point` to any point in its orbit.
pub fn schreier_vector(point: usize, generators: &[Perm], n: usize) -> (Vec<usize>, Vec<usize>) {
    let mut nu = vec![usize::MAX; n];
    let mut w = vec![usize::MAX; n];
    let mut seen = vec![false; n];
    let mut queue = VecDeque::new();

    if point < n {
        seen[point] = true;
        nu[point] = point;
        queue.push_back(point);
    }

    while let Some(current) = queue.pop_front() {
        for (gen_index, generator) in generators.iter().enumerate() {
            let next = on_points(current, generator);
            if !seen[next] {
                seen[next] = true;
                nu[next] = current;
                w[next] = gen_index;
                queue.push_back(next);
            }
        }
    }

    (nu, w)
}

/// Trace back through a Schreier vector to find the group element
/// that maps `point` to `target`. Returns the permutation.
pub fn trace_schreier(
    target: usize,
    point: usize,
    nu: &[usize],
    w: &[usize],
    generators: &[Perm],
    n: usize,
) -> Perm {
    if target >= n || point >= n || nu.get(target).copied().unwrap_or(usize::MAX) == usize::MAX {
        return identity(n);
    }
    let mut current = target;
    let mut trace = identity(n);
    while current != point {
        let gen_index = w[current];
        if gen_index == usize::MAX {
            return identity(n);
        }
        let generator = inverse(&generators[gen_index]);
        trace = product(&generator, &trace);
        current = nu[current];
    }
    trace
}

fn fixes_all(points: &[usize], p: &[usize]) -> bool {
    points.iter().all(|point| p[*point] == *point)
}

fn contains_perm(perms: &[Perm], candidate: &[usize]) -> bool {
    perms.iter().any(|perm| perm == candidate)
}

/// Compute the stabilizer subgroup of a set of points.
/// Given generators of a group G, return generators of Stab_G(points).
pub fn stabilizer(points: &[usize], generators: &[Perm], n: usize) -> Vec<Perm> {
    let mut stabilizer_gens = Vec::new();

    for generator in generators {
        if fixes_all(points, generator) && !contains_perm(&stabilizer_gens, generator) {
            stabilizer_gens.push(generator.clone());
        }
    }

    if points.is_empty() {
        return stabilizer_gens;
    }

    let base = points[0];
    let (nu, w) = schreier_vector(base, generators, n);
    let orbit_points: Vec<usize> = (0..n)
        .filter(|point| nu[*point] != usize::MAX)
        .collect();

    for orbit_point in orbit_points {
        let trace_to_orbit = trace_schreier(orbit_point, base, &nu, &w, generators, n);
        for generator in generators {
            let moved = on_points(orbit_point, generator);
            if moved >= n || nu[moved] == usize::MAX {
                continue;
            }
            let trace_to_moved = trace_schreier(moved, base, &nu, &w, generators, n);
            let schreier_gen = product(
                &product(&trace_to_orbit, generator),
                &inverse(&trace_to_moved),
            );
            if fixes_all(points, &schreier_gen) && !is_identity(&schreier_gen) && !contains_perm(&stabilizer_gens, &schreier_gen) {
                stabilizer_gens.push(schreier_gen);
            }
        }
    }

    stabilizer_gens
}

/// Count the number of inversions in a permutation (for computing sign).
pub fn sign(p: &[usize]) -> i32 {
    let mut inversions = 0usize;
    for i in 0..p.len() {
        for j in (i + 1)..p.len() {
            if p[i] > p[j] {
                inversions += 1;
            }
        }
    }
    if inversions % 2 == 0 { 1 } else { -1 }
}

/// Create a transposition: swaps positions i and j, fixes everything else.
pub fn transposition(n: usize, i: usize, j: usize) -> Perm {
    let mut p = identity(n);
    p.swap(i, j);
    p
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn identity_is_identity() {
        let id = identity(5);
        assert!(is_identity(&id));
    }

    #[test]
    fn product_with_identity() {
        let id = identity(4);
        let p = vec![1, 0, 3, 2];
        assert_eq!(product(&p, &id), p);
        assert_eq!(product(&id, &p), p);
    }

    #[test]
    fn inverse_undoes() {
        let p = vec![1, 2, 0, 3];
        let ip = inverse(&p);
        let result = product(&p, &ip);
        assert!(is_identity(&result));
    }

    #[test]
    fn orbit_of_cycle() {
        let gen = vec![vec![1, 2, 0, 3]];
        let orb = orbit(0, &gen);
        assert_eq!(orb.len(), 3);
        assert!(orb.contains(&0));
        assert!(orb.contains(&1));
        assert!(orb.contains(&2));
    }

    #[test]
    fn sign_of_transposition() {
        let p = transposition(4, 0, 1);
        assert_eq!(sign(&p), -1);
    }

    #[test]
    fn sign_of_identity() {
        assert_eq!(sign(&identity(5)), 1);
    }

    #[test]
    fn sign_of_3cycle() {
        let p = vec![1, 2, 0, 3];
        assert_eq!(sign(&p), 1);
    }

    #[test]
    fn stabilizer_of_point() {
        let gens = vec![vec![1, 0, 2], vec![0, 2, 1]];
        let stab = stabilizer(&[0], &gens, 3);
        for g in &stab {
            assert_eq!(g[0], 0, "stabilizer element doesn't fix 0: {:?}", g);
        }
    }
}
