[package]
name = "ax-ir"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
lasso = { workspace = true, features = ["multi-threaded"] }
num-bigint = { workspace = true }
num-rational = { workspace = true }
num-traits = { workspace = true }
num-integer = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
