[package]
name = "ax-tensor"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
ax-forms = { path = "../ax-forms" }
ax-ir = { path = "../ax-ir" }
ax-linalg = { path = "../ax-linalg" }
ax-perm = { path = "../ax-perm" }
ax-trace = { path = "../ax-trace" }
ax-young = { path = "../ax-young" }
lasso = { workspace = true }
num-bigint = { workspace = true }
num-rational = { workspace = true }
num-traits = { workspace = true }
rayon = "1"
thiserror = { workspace = true }

[dev-dependencies]
ax-core-ir = { path = "../ax-core-ir" }
ax-eval = { path = "../ax-eval" }
ax-spinor = { path = "../ax-spinor" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
