[package]
name = "ax-plugin-host"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
serde_json = { workspace = true }
ax-ai-proto = { path = "../ax-ai-proto" }
ax-ir = { path = "../ax-ir" }
ax-plugin-api = { path = "../ax-plugin-api" }
ax-render = { path = "../ax-render" }
ax-syntax = { path = "../ax-syntax" }
num-traits = { workspace = true }

wasmtime = "19.0"

[dev-dependencies]
axp-echo = { path = "../../plugins/axp-echo" }
axp-sparse-demo = { path = "../../plugins/axp-sparse-demo" }
